name = "tesla-stock-notifier"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "TESLA_VIN_STORE"
id = "f116f12f81fe462ab124f8ca80fe7468"

[observability.logs]
enabled = true